import { User, RecommendedAction, Project, Opportunity, Skill, Proof, AppMetrics, Recruiter, RecruitmentOutcome, OutcomeStatus, ValidationSource, MarketFeedback, Contribution } from '../types';

const generateMockValidationSources = (id: string, confidence: number): ValidationSource[] => [
  { id: `vs1_${id}`, type: 'causal', label: 'Causalité Technique', weight: 0.3, confidence, status: 'verified' },
  { id: `vs2_${id}`, type: 'human_confirmation', label: 'Confirmation Mutuelle', weight: 0.2, confidence: 100, status: 'verified' },
  { id: `vs3_${id}`, type: 'external_signal', label: 'Signaux Externes', weight: 0.3, confidence: Math.max(0, confidence - 10), status: confidence > 70 ? 'verified' : 'pending' },
  { id: `vs4_${id}`, type: 'peer_validation', label: 'Validation Marché', weight: 0.1, confidence: 90, status: 'verified' },
  { id: `vs5_${id}`, type: 'ecosystemic_signal', label: 'Impact Écosystémique', weight: 0.1, confidence: 100, status: 'verified' }
];

export const mockRecruiter: Recruiter = {
  id: 'r1',
  name: 'Jean-Marc Durand',
  company: 'Logistique Globale Solutions',
  companyDomain: 'logistique-globale.com',
  emailVerified: true,
  verifiedBadge: true,
  avatar: 'https://i.pravatar.cc/150?u=r1',
  role: 'Directeur des Opérations'
};

export const mockUser: User = {
  id: 'u1',
  tenantId: 'demo_tenant',
  name: 'Marc Lefebvre',
  role: 'Directeur des Opérations Logistiques',
  avatar: 'https://i.pravatar.cc/150?u=marclefebvre',
  rawScore: 785,
  weightedScore: 842,
  impactScore: 88,
  objective: 'employment',
  confidenceIndex: 94,
  reliabilityScore: 98,
  reputationScore: 92,
  identityStatus: 'verified',
  identityVerifiedAt: '2024-01-15T09:00:00Z',
  trustFactors: {
    reliability: 0.98,
    validatorDiversity: 0.85,
    identityStrength: 1.0,
    sourceQuality: 0.92,
    reputationHistory: 0.95,
    temporalFreshness: 0.88,
    impactWeight: 0.92,
    consistencyScore: 0.94,
    anomalyScore: 0.02
  },
  topSkills: ['Logistique Terrain', 'Optimisation Hub', 'Management de Crise', 'Négociation Fournisseurs'],
  penaltyScore: 0,
  validatorTrustScore: 0.92,
  marketTrustIndex: 94,
  trustHistory: [
    { timestamp: '2024-01-01T10:00:00Z', anomalyScore: 0.05, consistencyScore: 0.85, validatorDiversity: 0.75 },
    { timestamp: '2024-02-01T10:00:00Z', anomalyScore: 0.03, consistencyScore: 0.90, validatorDiversity: 0.80 },
    { timestamp: '2024-03-01T10:00:00Z', anomalyScore: 0.02, consistencyScore: 0.94, validatorDiversity: 0.85 }
  ],
  lastActivity: '2024-03-30T10:00:00Z',
  externalReferences: {
    linkedInUpdate: 'https://linkedin.com/posts/ndepo_hired-logistique',
  },
  aiSummary: "Expert terrain ayant transformé 3 hubs en difficulté en centres de profit optimisés. Spécialiste de l'action rapide (Action) avec preuves de gains de productivité de +20% à chaque mission (Résultat).",
  opportunityProjection: "Candidat idéal pour des postes de Direction de Site ou de Supply Chain hautement opérationnels.",
  retentionDay1: true,
  retentionDay7: false,
  contactStatus: 'none',
  applications: [],
  auditLog: [],
  skills: [
    { id: 's1', name: 'Logistique', validated: true, proofsCount: 15 },
    { id: 's2', name: 'Opérations', validated: true, proofsCount: 10 },
    { id: 's3', name: 'Team Lead', validated: true, proofsCount: 8 },
    { id: 's4', name: 'Optimisation', validated: true, proofsCount: 12 },
  ],
  marketValueSignature: {
    execution: 45,
    decision: 20,
    coordination: 15,
    knowledge: 10,
    softProcedure: 5,
    agility: 5,
    decisionVelocity: 94,
    leverage: 90,
    impactLevel: 'high',
    totalValueCreated: 4200,
    topImpactProjects: ['p1']
  }
};

export const mockContributions: Contribution[] = [
  {
    id: 'c1',
    projectId: 'p1',
    userId: 'u1',
    type: 'execution',
    title: 'Automatisation Hub Marseille',
    description: 'Installation et paramétrage du nouveau convoyeur (Action) → Productivité augmentée de +25% sur le tri nocturne (Impact) → Enregistrements système certifiés (Preuve).',
    timestamp: '2024-01-10T10:00:00Z',
    impactScore: 95,
    leverageScore: 90,
    evidenceIds: ['pr1'],
    metadata: { technicalCausality: 0.9, peerValidation: 0.95, economicSignal: 0.8 }
  },
  {
    id: 'c2',
    projectId: 'p1',
    userId: 'u1',
    type: 'execution',
    title: 'Digitalisation des tournées',
    description: 'Transition complète de 50 chauffeurs vers l\'application mobile (Action) → Zéro perte de bordereaux sur un trimestre (Impact) → Logs de tracking GPS (Preuve).',
    timestamp: '2024-01-20T14:00:00Z',
    impactScore: 88,
    leverageScore: 40,
    causalDependencies: ['c1'],
    evidenceIds: ['pr2'],
    metadata: { technicalCausality: 0.85, peerValidation: 0.9, economicSignal: 0.7 }
  },
  {
    id: 'c3',
    projectId: 'p2',
    userId: 'u1',
    type: 'decision',
    title: 'Négociation Contrat Transport',
    description: 'Mise en concurrence sélective des prestataires (Action) → Économie de 120k€ sur le budget annuel (Impact) → Contrats signés (Preuve).',
    timestamp: '2024-02-15T14:00:00Z',
    impactScore: 92,
    leverageScore: 95,
    evidenceIds: ['pr3'],
    metadata: { technicalCausality: 0.7, peerValidation: 0.9, economicSignal: 0.8 }
  }
];

export const mockMetrics: AppMetrics = {
  totalActions: 1240,
  totalReturns: 450,
  recruiterConversions: 85,
  activeUsers: 320,
  marketValidation: {
    totalContacts: 482,
    totalContactSessions: 1240,
    totalInterviews: 156,
    lockedProcesses: 84,
    realHires: 42,
    verifiedHires: 12,
    highConfidenceHires: 8,
    lowConfidenceHires: 4,
    fraudSuspicionRate: 5.2,
    attributionRate: 28.5,
    avgTimeToHireDays: 18
  },
  systemIntegrity: {
    verifiedOutcomeRatio: 35,
    reliableProfileRatio: 82,
    anomalyRate: 2.4,
    collusionSuspicionRate: 1.2,
    validatorDiversityIndex: 0.74,
    publicProofRatio: 68,
    independentValidationRate: 85,
    avgReputationScore: 76,
    impactProofRatio: 42,
    hireLinkedProofRate: 35,
    avgImpactScore: 76
  }
};

export const mockOutcomes: RecruitmentOutcome[] = [
  {
    id: 'ro1',
    tenantId: 'demo_tenant',
    userId: 'u1',
    recruiterId: 'rec1',
    status: 'hired',
    companyName: 'TechCorp',
    role: 'Senior Frontend Engineer',
    linkedProofIds: ['pr1', 'pr2', 'pr_kb_1', 'pr_nps_1', 'pr_agility_1'],
    contactSessions: [
      { 
        id: 'sess_99a1', 
        method: 'email', 
        timestamp: '2024-01-10T10:00:00Z', 
        trackingUrl: 'https://workproof.os/t/sess_99a1',
        messages: [
          { id: 'm1', senderId: 'rec1', senderType: 'recruiter', content: 'Bonjour, votre profil nous intéresse.', timestamp: '2024-01-10T10:00:00Z' },
          { id: 'm2', senderId: 'u1', senderType: 'candidate', content: 'Merci, je suis disponible pour en discuter.', timestamp: '2024-01-10T11:00:00Z' }
        ]
      }
    ],
    isLockedToPlatform: true,
    candidateConfirmed: true,
    recruiterConfirmed: true,
    confirmationTimestamp: '2024-02-15T14:30:00Z',
    attributionConfidenceScore: 100,
    truthState: 'verified',
    verdict: 'highly_reliable',
    validationSources: generateMockValidationSources('ro1', 100),
    marketFeedback: [
      { id: 'mf1', actorId: 'r1', actorType: 'recruiter', targetId: 'ro1', type: 'trust_signal', value: true, timestamp: '2024-02-16T10:00:00Z' }
    ],
    isVerifiedAttribution: true,
    attributionProof: '0xabc123...',
    sector: 'FinTech',
    experienceLevel: 'senior',
    location: 'Paris, FR',
    commitment: {
      id: 'commit_ro1',
      type: 'economic_activity_signal',
      timestamp: '2024-02-15T14:30:00Z',
      actorId: 'rec1',
      hash: 'anchor_ro1_99a1',
      status: 'active',
      economicValue: 5000,
      currency: 'EUR',
      metadata: {
        source: 'platform_signal_capture_layer',
        causalityVerified: true,
        confidenceWeight: 'critical'
      }
    },
    riskFlags: [],
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-02-15T14:30:00Z'
  },
  {
    id: 'ro2',
    tenantId: 'demo_tenant',
    userId: 'u2',
    recruiterId: 'rec2',
    status: 'interview_scheduled',
    companyName: 'DesignStudio',
    role: 'Lead Product Designer',
    linkedProofIds: ['p3'],
    contactSessions: [
      { 
        id: 'sess_88b2', 
        method: 'whatsapp', 
        timestamp: '2024-03-01T09:00:00Z', 
        trackingUrl: 'https://workproof.os/t/sess_88b2',
        messages: []
      }
    ],
    isLockedToPlatform: false,
    candidateConfirmed: false,
    recruiterConfirmed: false,
    attributionConfidenceScore: 30,
    truthState: 'unverified',
    verdict: 'risky',
    validationSources: generateMockValidationSources('ro2', 30),
    marketFeedback: [],
    isVerifiedAttribution: false,
    riskFlags: ['Unverified Channel', 'Absence d\'interaction réelle'],
    sector: 'Design',
    experienceLevel: 'lead',
    location: 'Remote',
    createdAt: '2024-03-01T09:00:00Z',
    updatedAt: '2024-03-05T11:00:00Z'
  },
  {
    id: 'ro3',
    tenantId: 'demo_tenant',
    userId: 'u1',
    recruiterId: 'rec3',
    status: 'rejected',
    companyName: 'InnoSoft',
    role: 'Fullstack Dev',
    linkedProofIds: [],
    contactSessions: [],
    isLockedToPlatform: false,
    candidateConfirmed: false,
    recruiterConfirmed: true,
    attributionConfidenceScore: 10,
    truthState: 'disputed',
    verdict: 'risky',
    validationSources: generateMockValidationSources('ro3', 10),
    marketFeedback: [],
    disputeStatus: 'open',
    disputeHistory: [
      {
        id: 'disp-1',
        timestamp: '2024-03-20T10:00:00Z',
        actorId: 'u1',
        reason: "Le recruteur déclare un refus mais j'ai reçu un signal d'engagement par email.",
        status: 'open'
      }
    ],
    isVerifiedAttribution: false,
    riskFlags: ['Incohérence de confirmation'],
    sector: 'SaaS',
    experienceLevel: 'intermediate',
    location: 'Lyon, FR',
    createdAt: '2024-03-10T11:00:00Z',
    updatedAt: '2024-03-20T10:00:00Z'
  },
  {
    id: 'ro4',
    tenantId: 'demo_tenant',
    userId: 'u1',
    recruiterId: 'rec2',
    status: 'offer_sent',
    companyName: 'DesignStudio',
    role: 'Product Designer',
    linkedProofIds: [],
    contactSessions: [
      { 
        id: 'sess_77c3', 
        method: 'platform', 
        timestamp: '2024-03-10T10:00:00Z', 
        trackingUrl: 'https://workproof.os/t/sess_77c3',
        messages: [
          { id: 'm3', senderId: 'rec2', senderType: 'recruiter', content: 'Votre profil est excellent.', timestamp: '2024-03-10T10:00:00Z' }
        ]
      }
    ],
    isLockedToPlatform: true,
    candidateConfirmed: false,
    recruiterConfirmed: true,
    attributionConfidenceScore: 65,
    truthState: 'probable',
    verdict: 'uncertain',
    validationSources: generateMockValidationSources('ro4', 65),
    marketFeedback: [],
    isVerifiedAttribution: false,
    commitment: {
      id: 'commit_ro4',
      type: 'mutual_commitment_signal',
      timestamp: '2024-03-12T15:00:00Z',
      actorId: 'rec2',
      hash: 'anchor_ro4_77c3',
      status: 'active',
      metadata: {
        source: 'platform_signal_capture_layer',
        causalityVerified: true,
        confidenceWeight: 'high'
      }
    },
    riskFlags: [],
    sector: 'Design',
    experienceLevel: 'intermediate',
    location: 'Bordeaux, FR',
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-03-12T15:00:00Z'
  }
];

// Market Simulation Dataset
export const mockUsers: User[] = [
  mockUser,
  {
    id: 'u2',
    tenantId: 'demo_tenant',
    name: 'Sarah Jenkins',
    role: 'Responsable Logistique & Supply Chain',
    avatar: 'https://i.pravatar.cc/150?u=sarah',
    rawScore: 980,
    weightedScore: 710,
    impactScore: 82,
    objective: 'employment',
    confidenceIndex: 88,
    reliabilityScore: 88,
    reputationScore: 75,
    identityStatus: 'verified',
    trustFactors: {
      reliability: 0.88,
      validatorDiversity: 0.4,
      identityStrength: 1.0,
      sourceQuality: 0.5,
      reputationHistory: 0.6,
      temporalFreshness: 0.9,
      impactWeight: 0.85,
      consistencyScore: 0.7,
      anomalyScore: 0.05
    },
    auditLog: [],
    topSkills: ['Gestion de Stocks', 'Planification', 'Optimisation de Flux'],
    penaltyScore: 0,
    validatorTrustScore: 0.85,
    marketTrustIndex: 82,
    aiSummary: "Les livraisons prenaient 5 jours entraînant des pertes clients (Avant) → Réorganisation complète des tournées et des zones de stockage (Action) → Délais réduits à 2 jours et satisfaction client +40% (Après) → Validé par rapport d'audit logistique certifié et feedback clients (Preuve). Impact systémique : Réduction de l'empreinte carbone de 15% et renouvellement de 95% des contrats annuels.",
    opportunityProjection: "Profil idéal pour des centres de distribution en phase de modernisation.",
    skills: [
      { id: 's5', name: 'Logistique', validated: true, proofsCount: 10 },
      { id: 's6', name: 'Automatisation', validated: true, proofsCount: 14 },
    ],
    marketValueSignature: {
      execution: 70,
      decision: 5,
      coordination: 5,
      knowledge: 10,
      softProcedure: 5,
      agility: 5,
      decisionVelocity: 68,
      leverage: 48,
      impactLevel: 'medium',
      totalValueCreated: 1350,
      topImpactProjects: ['p1']
    }
  },
  {
    id: 'u3',
    tenantId: 'demo_tenant',
    name: 'Marc Lemoine',
    role: 'Directeur des Opérations RH',
    avatar: 'https://i.pravatar.cc/150?u=marc',
    rawScore: 1500,
    weightedScore: 920,
    impactScore: 95,
    objective: 'employment',
    confidenceIndex: 97,
    reliabilityScore: 97,
    reputationScore: 94,
    identityStatus: 'verified',
    trustFactors: {
      reliability: 0.97,
      validatorDiversity: 0.9,
      identityStrength: 1.0,
      sourceQuality: 0.95,
      reputationHistory: 0.98,
      temporalFreshness: 0.92,
      impactWeight: 0.98,
      consistencyScore: 0.96,
      anomalyScore: 0.01
    },
    auditLog: [],
    topSkills: ['Recrutement Stratégique', 'Culture d\'Entreprise', 'Gestion de Crise'],
    penaltyScore: 0,
    validatorTrustScore: 0.94,
    marketTrustIndex: 96,
    aiSummary: "Le turnover stagnait à 25% impactant la productivité (Avant) → Implémentation d'une politique de télétravail hybride et refonte du onboarding (Action) → Réduction du turnover à 7% et climat social +30% (Après) → Validé par enquête de climat social annuelle et baisse des coûts de recrutement (Preuve). Impact systémique : Gain de productivité globale de 18% et positionnement en tant que 'Top Employer' sectoriel.",
    opportunityProjection: "Profil stratégique pour des entreprises en forte croissance ou en transformation culturelle.",
    skills: [
      { id: 's7', name: 'RH', validated: true, proofsCount: 20 },
      { id: 's8', name: 'Culture', validated: true, proofsCount: 18 },
    ],
    marketValueSignature: {
      execution: 25,
      decision: 20,
      coordination: 20,
      knowledge: 15,
      softProcedure: 15,
      agility: 5,
      decisionVelocity: 95,
      leverage: 92,
      impactLevel: 'high',
      totalValueCreated: 4200,
      topImpactProjects: ['p1', 'p2']
    }
  },
  {
    id: 'u4',
    tenantId: 'demo_tenant',
    name: 'Julie Bernard',
    role: 'Artisane Ébéniste d\'Art',
    avatar: 'https://i.pravatar.cc/150?u=julie',
    rawScore: 1200,
    weightedScore: 880,
    impactScore: 90,
    objective: 'entrepreneur',
    confidenceIndex: 92,
    reliabilityScore: 92,
    reputationScore: 88,
    identityStatus: 'verified',
    trustFactors: {
      reliability: 0.92,
      validatorDiversity: 0.7,
      identityStrength: 1.0,
      sourceQuality: 0.8,
      reputationHistory: 0.85,
      temporalFreshness: 0.9,
      impactWeight: 0.9,
      consistencyScore: 0.88,
      anomalyScore: 0.03
    },
    auditLog: [],
    topSkills: ['Design de Mobilier', 'Restauration de Patrimoine', 'Vente Directe'],
    penaltyScore: 0,
    marketTrustIndex: 90,
    aiSummary: "Le mobilier d'un monument historique se dégradait faute de soins (Avant) → Restauration complète utilisant des techniques traditionnelles du XVIIe (Action) → Conservation du patrimoine assurée pour 50 ans et réouverture au public (Après) → Certifié par les Bâtiments de France et rapport de conservation (Preuve). Impact systémique : Relance du tourisme local (+15%) et transmission du savoir-faire à 3 apprentis.",
    opportunityProjection: "Potentiel élevé pour des projets de luxe ou de conservation institutionnelle.",
    skills: [
      { id: 's9', name: 'Ébénisterie', validated: true, proofsCount: 25 },
      { id: 's10', name: 'Patrimoine', validated: true, proofsCount: 12 },
    ],
    marketValueSignature: {
      execution: 55,
      decision: 10,
      coordination: 10,
      knowledge: 15,
      softProcedure: 5,
      agility: 5,
      decisionVelocity: 82,
      leverage: 65,
      impactLevel: 'high',
      totalValueCreated: 3400,
      topImpactProjects: ['p1']
    }
  },
  {
    id: 'u5',
    tenantId: 'demo_tenant',
    name: 'Elena Rodriguez',
    role: 'Lead Développeuse Fullstack',
    avatar: 'https://i.pravatar.cc/150?u=elena',
    rawScore: 1100,
    weightedScore: 940,
    impactScore: 92,
    objective: 'employment',
    confidenceIndex: 95,
    reliabilityScore: 95,
    reputationScore: 90,
    identityStatus: 'verified',
    trustFactors: {
      reliability: 0.95,
      validatorDiversity: 0.8,
      identityStrength: 1.0,
      sourceQuality: 0.9,
      reputationHistory: 0.9,
      temporalFreshness: 0.95,
      impactWeight: 0.92,
      consistencyScore: 0.94,
      anomalyScore: 0.02
    },
    auditLog: [],
    topSkills: ['Architecture Cloud', 'React/Node.js', 'DevOps'],
    penaltyScore: 0,
    marketTrustIndex: 94,
    aiSummary: "Temps de chargement élevé (>4s) et coûts serveurs excessifs (Avant) → Migration de l'infrastructure vers une architecture serverless et optimisation DB (Action) → Réduction des coûts de 35% et temps de chargement <800ms (Après) → Validé par factures AWS, logs CloudWatch et rapports de performance (Preuve). Impact systémique : Amélioration du SEO (+20 positions) et capacité de charge multipliée par 10 sans surcoût.",
    opportunityProjection: "Experte technique capable de porter des projets de scalabilité critique.",
    skills: [
      { id: 's11', name: 'Cloud', validated: true, proofsCount: 15 },
      { id: 's12', name: 'Architecture', validated: true, proofsCount: 10 },
    ],
    marketValueSignature: {
      execution: 40,
      decision: 20,
      coordination: 15,
      knowledge: 10,
      softProcedure: 10,
      agility: 5,
      decisionVelocity: 95,
      leverage: 88,
      impactLevel: 'high',
      totalValueCreated: 5000,
      topImpactProjects: ['p1']
    }
  },
  {
    id: 'u6',
    tenantId: 'demo_tenant',
    name: 'David Chen',
    role: 'Directeur de Restaurant',
    avatar: 'https://i.pravatar.cc/150?u=david',
    rawScore: 950,
    weightedScore: 820,
    impactScore: 85,
    objective: 'employment',
    confidenceIndex: 89,
    reliabilityScore: 89,
    reputationScore: 80,
    identityStatus: 'verified',
    trustFactors: {
      reliability: 0.89,
      validatorDiversity: 0.6,
      identityStrength: 1.0,
      sourceQuality: 0.7,
      reputationHistory: 0.75,
      temporalFreshness: 0.85,
      impactWeight: 0.8,
      consistencyScore: 0.82,
      anomalyScore: 0.04
    },
    auditLog: [],
    topSkills: ['Gestion de P&L', 'Management de Brigade', 'Expérience Client'],
    penaltyScore: 0,
    marketTrustIndex: 88,
    aiSummary: "Ticket moyen stagnant et gaspillage alimentaire élevé (Avant) → Lancement d'un concept de menu saisonnier et optimisation des stocks (Action) → Augmentation du ticket moyen de 15% et réduction du gaspillage de 20% (Après) → Validé par rapports de caisse annuels (Preuve).",
    opportunityProjection: "Profil opérationnel fort pour des groupes de restauration en expansion.",
    skills: [
      { id: 's13', name: 'Gestion', validated: true, proofsCount: 12 },
      { id: 's14', name: 'Management', validated: true, proofsCount: 18 },
    ],
    marketValueSignature: {
      execution: 50,
      decision: 15,
      coordination: 15,
      knowledge: 10,
      softProcedure: 5,
      agility: 5,
      decisionVelocity: 82,
      leverage: 70,
      impactLevel: 'medium',
      totalValueCreated: 2100,
      topImpactProjects: ['p1']
    }
  },
  {
    id: 'u7',
    tenantId: 'demo_tenant',
    name: 'Sophie Martin',
    role: 'Chef de Chantier BTP',
    avatar: 'https://i.pravatar.cc/150?u=sophie',
    rawScore: 1050,
    weightedScore: 850,
    impactScore: 88,
    objective: 'employment',
    confidenceIndex: 91,
    reliabilityScore: 91,
    reputationScore: 85,
    identityStatus: 'verified',
    trustFactors: {
      reliability: 0.91,
      validatorDiversity: 0.7,
      identityStrength: 1.0,
      sourceQuality: 0.8,
      reputationHistory: 0.8,
      temporalFreshness: 0.9,
      impactWeight: 0.88,
      consistencyScore: 0.85,
      anomalyScore: 0.03
    },
    auditLog: [],
    topSkills: ['Coordination de Travaux', 'Sécurité Chantier', 'Gestion de Planning'],
    penaltyScore: 0,
    marketTrustIndex: 90,
    aiSummary: "Retards récurrents sur les phases de gros œuvre (Avant) → Mise en place d'un système de suivi temps réel et coordination renforcée des sous-traitants (Action) → Livraison du projet avec 2 semaines d'avance (Après) → Validé par PV de réception sans réserve (Preuve).",
    opportunityProjection: "Profil rigoureux pour des chantiers d'envergure ou complexes.",
    skills: [
      { id: 's15', name: 'BTP', validated: true, proofsCount: 15 },
      { id: 's16', name: 'Coordination', validated: true, proofsCount: 22 },
    ],
    marketValueSignature: {
      execution: 75,
      decision: 5,
      coordination: 5,
      knowledge: 5,
      softProcedure: 5,
      agility: 5,
      decisionVelocity: 70,
      leverage: 55,
      impactLevel: 'high',
      totalValueCreated: 3500,
      topImpactProjects: ['p1']
    }
  },
  {
    id: 'u8',
    tenantId: 'demo_tenant',
    name: 'Thomas Morel',
    role: 'Commercial Terrain B2B',
    avatar: 'https://i.pravatar.cc/150?u=thomas',
    rawScore: 1150,
    weightedScore: 890,
    impactScore: 91,
    objective: 'employment',
    confidenceIndex: 93,
    reliabilityScore: 93,
    reputationScore: 87,
    identityStatus: 'verified',
    trustFactors: {
      reliability: 0.93,
      validatorDiversity: 0.8,
      identityStrength: 1.0,
      sourceQuality: 0.85,
      reputationHistory: 0.85,
      temporalFreshness: 0.92,
      impactWeight: 0.9,
      consistencyScore: 0.89,
      anomalyScore: 0.02
    },
    auditLog: [],
    topSkills: ['Prospection', 'Négociation', 'Gestion de Portefeuille'],
    penaltyScore: 0,
    marketTrustIndex: 92,
    aiSummary: "Pipeline de vente stagnant sur le secteur Nord (Avant) → Restructuration complète du funnel de prospection et ciblage stratégique (Action) → Augmentation du CA de 30% en 6 mois (Après) → Validé par extraits CRM certifiés (Preuve).",
    opportunityProjection: "Chasseur de haut niveau pour des marchés compétitifs.",
    skills: [
      { id: 's17', name: 'Vente', validated: true, proofsCount: 30 },
      { id: 's18', name: 'Négociation', validated: true, proofsCount: 25 },
    ],
    marketValueSignature: {
      execution: 50,
      decision: 15,
      coordination: 15,
      knowledge: 10,
      softProcedure: 5,
      agility: 5,
      decisionVelocity: 85,
      leverage: 80,
      impactLevel: 'high',
      totalValueCreated: 4200,
      topImpactProjects: ['p1']
    }
  },
  {
    id: 'u9',
    tenantId: 'demo_tenant',
    name: 'Dr. Claire Vallet',
    role: 'Infirmière Coordinatrice - Urgences',
    avatar: 'https://i.pravatar.cc/150?u=claire',
    rawScore: 1350,
    weightedScore: 910,
    impactScore: 94,
    objective: 'employment',
    confidenceIndex: 96,
    reliabilityScore: 96,
    reputationScore: 92,
    identityStatus: 'verified',
    trustFactors: {
      reliability: 0.96,
      validatorDiversity: 0.85,
      identityStrength: 1.0,
      sourceQuality: 0.94,
      reputationHistory: 0.95,
      temporalFreshness: 0.9,
      impactWeight: 0.94,
      consistencyScore: 0.92,
      anomalyScore: 0.01
    },
    auditLog: [],
    topSkills: ['Coordination de Soins', 'Gestion de Crise', 'Optimisation de Flux Patient'],
    penaltyScore: 0,
    marketTrustIndex: 95,
    aiSummary: "Temps d'attente moyen aux urgences de 4h (Avant) → Mise en place d'un protocole de tri dynamique et réorganisation des box (Action) → Réduction du temps d'attente à 1h30 et satisfaction patient +55% (Après) → Validé par rapports d'activité hospitaliers et feedback équipe médicale (Preuve). Impact systémique : Amélioration de la prise en charge des cas critiques (+25%) et réduction du stress des équipes.",
    opportunityProjection: "Profil de leadership exceptionnel pour des structures de santé complexes.",
    skills: [
      { id: 's19', name: 'Santé', validated: true, proofsCount: 18 },
      { id: 's20', name: 'Coordination', validated: true, proofsCount: 25 },
    ],
    marketValueSignature: {
      execution: 30,
      decision: 30,
      coordination: 15,
      knowledge: 10,
      softProcedure: 10,
      agility: 5,
      decisionVelocity: 94,
      leverage: 92,
      impactLevel: 'high',
      totalValueCreated: 4800,
      topImpactProjects: ['p1']
    }
  },
  {
    id: 'u10',
    tenantId: 'demo_tenant',
    name: 'Me Antoine Rivet',
    role: 'Avocat Associé - Droit des Affaires',
    avatar: 'https://i.pravatar.cc/150?u=antoine',
    rawScore: 1420,
    weightedScore: 930,
    impactScore: 96,
    objective: 'entrepreneur',
    confidenceIndex: 98,
    reliabilityScore: 98,
    reputationScore: 95,
    identityStatus: 'verified',
    trustFactors: {
      reliability: 0.98,
      validatorDiversity: 0.9,
      identityStrength: 1.0,
      sourceQuality: 0.96,
      reputationHistory: 0.97,
      temporalFreshness: 0.94,
      impactWeight: 0.96,
      consistencyScore: 0.97,
      anomalyScore: 0.01
    },
    auditLog: [],
    topSkills: ['Fusion-Acquisition', 'Négociation Stratégique', 'Conformité'],
    penaltyScore: 0,
    marketTrustIndex: 97,
    aiSummary: "Litige complexe bloquant une fusion de 50M€ (Avant) → Médiation stratégique et restructuration des clauses de garantie (Action) → Signature de l'accord en 3 semaines et économie de 5M€ de frais juridiques (Après) → Validé par actes notariés et témoignages clients (Preuve). Impact systémique : Sécurisation de 200 emplois et création d'un leader européen du secteur.",
    opportunityProjection: "Conseiller stratégique de haut vol pour des opérations de M&A.",
    skills: [
      { id: 's21', name: 'Droit', validated: true, proofsCount: 30 },
      { id: 's22', name: 'Stratégie', validated: true, proofsCount: 22 },
    ],
    marketValueSignature: {
      execution: 20,
      decision: 40,
      coordination: 15,
      knowledge: 10,
      softProcedure: 10,
      agility: 5,
      decisionVelocity: 98,
      leverage: 96,
      impactLevel: 'high',
      totalValueCreated: 6500,
      topImpactProjects: ['p1']
    }
  },
  ...Array.from({ length: 20 }).map((_, i) => ({
    id: `u${i + 11}`,
    tenantId: 'demo_tenant',
    name: `Professionnel ${i + 9}`,
    role: i % 4 === 0 ? 'Infirmier Coordinateur' : i % 4 === 1 ? 'Avocat Associé' : i % 4 === 2 ? 'Agriculteur Connecté' : 'Gestionnaire de Paie',
    avatar: `https://i.pravatar.cc/150?u=u${i + 9}`,
    rawScore: 400 + Math.random() * 1000,
    weightedScore: 300 + Math.random() * 600,
    impactScore: 60 + Math.random() * 40,
    objective: i % 3 === 0 ? 'freelance' : 'employment',
    confidenceIndex: 60 + Math.random() * 35,
    penaltyScore: 0,
    reliabilityScore: 60 + Math.random() * 35,
    reputationScore: 50 + Math.random() * 40,
    identityStatus: Math.random() > 0.5 ? 'verified' : 'unverified',
    trustFactors: {
      reliability: 0.6 + Math.random() * 0.3,
      validatorDiversity: Math.random(),
      identityStrength: Math.random() > 0.5 ? 1.0 : 0.2,
      sourceQuality: Math.random(),
      reputationHistory: Math.random(),
      temporalFreshness: Math.random(),
      impactWeight: Math.random(),
      consistencyScore: i % 3 === 0 ? 0.8 + Math.random() * 0.2 : (i % 3 === 1 ? 0.4 + Math.random() * 0.3 : 0.2 + Math.random() * 0.2),
      anomalyScore: i % 3 === 0 ? Math.random() * 0.2 : (i % 3 === 1 ? 0.3 + Math.random() * 0.2 : 0.65 + Math.random() * 0.3)
    },
    auditLog: [],
    topSkills: ['Expertise Métier', 'Coordination'],
    marketTrustIndex: 70,
    aiSummary: "Processus inefficaces (Avant) → Optimisation des flux de travail (Action) → Gain de productivité de 15% (Après) → Validé par indicateurs de performance (Preuve).",
    opportunityProjection: "Prêt pour des responsabilités accrues.",
    skills: [],
    marketValueSignature: {
      execution: 40 + Math.random() * 20,
      decision: 10 + Math.random() * 10,
      coordination: 10 + Math.random() * 10,
      knowledge: 5 + Math.random() * 5,
      softProcedure: 5 + Math.random() * 5,
      agility: 5 + Math.random() * 5,
      decisionVelocity: 60 + Math.random() * 30,
      leverage: 50 + Math.random() * 40,
      impactLevel: Math.random() > 0.5 ? 'high' : 'medium',
      totalValueCreated: 1000 + Math.random() * 3000,
      topImpactProjects: []
    }
  })) as User[]
];

export const mockActions: RecommendedAction[] = [
  {
    id: 'a1',
    description: 'Ajouter une preuve de résultat sur votre dernier projet',
    scoreGain: 45,
    opportunityImpact: 'Débloque 3 opportunités de Direction (Top 10%)',
    type: 'proof',
    priority: 'high',
    objectiveContext: ['employment', 'freelance']
  },
  {
    id: 'a2',
    description: 'Obtenir une validation par un ancien manager',
    scoreGain: 30,
    opportunityImpact: 'Augmente votre niveau de confiance de 15%',
    type: 'skill',
    priority: 'high',
    objectiveContext: ['employment', 'entrepreneur']
  }
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    userId: 'u1',
    title: 'Modernisation du Réseau Logistique Sud',
    description: 'A piloté la refonte complète des flux de distribution (Action) → Réduction des délais de 15% et des coûts de 12% (Impact) → Validé par audit externe (Preuve).',
    impact: 'Amélioration de la satisfaction client de 25% et optimisation des coûts opérationnels.',
    role: 'Directeur de Projet',
    date: '2023 - 2024',
    status: 'completed',
    industry: 'logistics',
    impactLevel: 'high',
    contributionIds: ['c1', 'c2', 'c3', 'c4', 'c5'],
    projectImpactScore: 1850,
    projectCredibilityIndex: 96,
    proofs: [
      { 
        id: 'pr1', 
        title: 'Rapport d\'Audit de Performance 2023', 
        description: 'Analyse chiffrée des gains d\'efficacité après déploiement.',
        type: 'document', 
        url: '#', 
        rawSourceUrl: 'https://storage.logistique.com/reports/audit-2023.pdf',
        isPubliclyVerifiable: true,
        verified: true, 
        verificationLevel: 'high',
        validatorId: 'v1',
        validatorName: 'Jean-Marc Durand (Directeur Opérations)',
        validatorType: 'expert',
        validatorRole: 'manager',
        validatorDomain: 'logistique-globale.com',
        date: '2023-12-15',
        confidenceScore: 98,
        impactScore: 95,
        impactLevel: 'high',
        usageCount: 150,
        context: 'production',
        linkedOutcomeId: 'app1',
        hash: 'sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        authorIdentityLinked: true,
        sourceQuality: 0.95,
        externalCheckStatus: 'success',
        externalMetadata: {
          extractedTitle: 'Audit Performance 2023',
          extractedAuthor: 'Alexandre Dupont',
          lastCheckedAt: '2024-03-25T10:05:00Z'
        }
      },
      { 
        id: 'pr2', 
        title: 'Logs d\'Intégration CRM', 
        description: 'Preuve technique de la synchronisation des données sur 12 agences.',
        type: 'code', 
        url: 'https://github.com/org/crm-sync/commits', 
        rawSourceUrl: 'https://github.com/org/crm-sync/commits',
        isPubliclyVerifiable: false,
        verified: true, 
        verificationLevel: 'medium',
        validatorId: 'v2',
        validatorName: 'Système Automatisé',
        validatorType: 'automated',
        date: '2024-01-20',
        confidenceScore: 85,
        impactScore: 88,
        impactLevel: 'medium',
        usageCount: 45,
        context: 'production',
        hash: 'sha256:f4c1...',
        authorIdentityLinked: true,
        sourceQuality: 0.9,
        externalCheckStatus: 'success'
      },
      { 
        id: 'pr3', 
        title: 'Attestation de Gain de Part de Marché', 
        description: 'Document officiel confirmant la croissance de 30% du CA.',
        type: 'document', 
        url: '#', 
        rawSourceUrl: 'https://storage.logistique.com/reports/market-share-2024.pdf',
        isPubliclyVerifiable: true,
        verified: true, 
        verificationLevel: 'high',
        validatorId: 'v3',
        validatorName: 'Cabinet d\'Audit Externe',
        validatorType: 'expert',
        date: '2024-02-10',
        confidenceScore: 95,
        impactScore: 92,
        impactLevel: 'high',
        usageCount: 80,
        context: 'production',
        hash: 'sha256:g5d2...',
        authorIdentityLinked: true,
        sourceQuality: 0.98,
        externalCheckStatus: 'success'
      },
      {
        id: 'pr_kb_1',
        title: 'Wiki de Capitalisation Savoir',
        description: 'Ensemble de 15 guides de procédures logistiques documentés.',
        type: 'knowledge_base',
        url: '#',
        rawSourceUrl: 'https://confluence.logistique.com/kb/logistics-2024',
        isPubliclyVerifiable: false,
        verified: true,
        verificationLevel: 'high',
        validatorId: 'v2',
        validatorName: 'Sophie Martin (Responsable RH)',
        validatorType: 'peer',
        validatorRole: 'peer',
        validatorDomain: 'logistique-globale.com',
        date: '2024-02-15',
        confidenceScore: 92,
        impactScore: 88,
        impactLevel: 'medium',
        usageCount: 45,
        context: 'internal',
        linkedOutcomeId: 'app1',
        hash: 'sha256:kb_hash_123',
        authorIdentityLinked: true,
        sourceQuality: 0.9,
        externalCheckStatus: 'success',
        externalMetadata: {
          extractedTitle: 'Logistics KB 2024',
          lastCheckedAt: '2024-03-25T10:05:00Z'
        }
      },
      {
        id: 'pr_nps_1',
        title: 'Rapport NPS Inter-Équipes Q1',
        description: 'Mesure de l\'impact de la médiation sur la fluidité opérationnelle.',
        type: 'nps_feedback',
        url: '#',
        rawSourceUrl: 'https://survey.logistique.com/nps/q1-2024',
        isPubliclyVerifiable: false,
        verified: true,
        verificationLevel: 'medium',
        validatorId: 'v3',
        validatorName: 'Marc Lefebvre (Chef de Projet Ventes)',
        validatorType: 'peer',
        validatorRole: 'peer',
        validatorDomain: 'logistique-globale.com',
        date: '2024-03-01',
        confidenceScore: 95,
        impactScore: 92,
        impactLevel: 'high',
        usageCount: 12,
        context: 'internal',
        linkedOutcomeId: 'app1',
        hash: 'sha256:nps_hash_456',
        authorIdentityLinked: true,
        sourceQuality: 0.95,
        externalCheckStatus: 'success',
        externalMetadata: {
          extractedTitle: 'Internal NPS Report Q1',
          lastCheckedAt: '2024-03-25T10:05:00Z'
        }
      },
      {
        id: 'pr_agility_1',
        title: 'Traces d\'Adoption Airtable',
        description: 'Logs d\'activité montrant la migration effective vers les nouveaux outils.',
        type: 'agility_trace',
        url: '#',
        rawSourceUrl: 'https://airtable.com/activity/logistics-migration',
        isPubliclyVerifiable: true,
        verified: true,
        verificationLevel: 'high',
        validatorId: 'system',
        validatorName: 'Système de Monitoring',
        validatorType: 'system',
        validatorRole: 'system',
        validatorDomain: 'airtable.com',
        date: '2024-03-20',
        confidenceScore: 99,
        impactScore: 85,
        impactLevel: 'medium',
        usageCount: 88,
        context: 'production',
        linkedOutcomeId: 'app1',
        hash: 'sha256:agility_hash_789',
        authorIdentityLinked: true,
        sourceQuality: 1.0,
        externalCheckStatus: 'success',
        externalMetadata: {
          extractedTitle: 'Airtable Activity Log',
          lastCheckedAt: '2024-03-25T10:05:00Z'
        }
      }
    ]
  },
  {
    id: 'p2',
    userId: 'u1',
    title: 'Optimisation Algorithmique Trading HFT',
    description: 'Réduction de la latence d\'exécution de 5ms à 2ms sur les marchés asiatiques.',
    impact: 'Augmentation du profit journalier de 8% et réduction du slippage.',
    role: 'Lead Developer Quant',
    date: '2022 - 2023',
    status: 'completed',
    industry: 'finance',
    impactLevel: 'high',
    contributionIds: [], // To be populated if needed
    projectImpactScore: 1200,
    projectCredibilityIndex: 88,
    proofs: []
  },
  {
    id: 'p3',
    userId: 'u1',
    title: 'Plateforme Télémédecine Régionale',
    description: 'Déploiement d\'un système de consultation à distance pour 50 cliniques.',
    impact: 'Accès aux soins facilité pour 200k patients en zone rurale.',
    role: 'Product Manager',
    date: '2021 - 2022',
    status: 'completed',
    industry: 'healthcare',
    impactLevel: 'medium',
    contributionIds: [],
    projectImpactScore: 650,
    projectCredibilityIndex: 78,
    proofs: []
  },
  {
    id: 'p4',
    userId: 'u1',
    title: 'Système de Recommandation E-commerce',
    description: 'Mise en place d\'un moteur de recommandation basé sur le filtrage collaboratif.',
    impact: 'Augmentation du panier moyen de 12%.',
    role: 'Data Scientist',
    date: '2023',
    status: 'ongoing',
    industry: 'retail',
    impactLevel: 'medium',
    contributionIds: [],
    projectImpactScore: 350,
    projectCredibilityIndex: 65,
    proofs: []
  }
];

export const mockOpportunities: Opportunity[] = [
  {
    id: 'o1',
    title: 'Directeur de Projet Stratégique',
    company: 'Logistique Globale Solutions',
    matchScore: 92,
    skillGap: ['Gestion de crise'],
    matchedSkills: ['Management', 'Stratégie', 'Optimisation'],
    requiredSkills: ['Management', 'Stratégie', 'Optimisation', 'Gestion de crise'],
    description: 'Piloter la transformation digitale des entrepôts européens.',
    aiExplanation: 'Votre expérience en optimisation de réseau est parfaitement alignée avec nos enjeux actuels.',
    potentialScoreGain: 18,
    relativePosition: 3,
    successProbability: 88,
    sector: 'Logistique',
    experienceLevel: 'senior',
    location: 'Lyon / Remote',
    createdAt: '2024-03-20T10:00:00Z'
  },
  {
    id: 'o2',
    title: 'Responsable de la Performance Opérationnelle',
    company: 'Retail Excellence',
    matchScore: 85,
    skillGap: ['Anglais courant'],
    matchedSkills: ['Optimisation', 'Management'],
    requiredSkills: ['Optimisation', 'Management', 'Anglais courant'],
    description: 'Améliorer l\'efficacité des points de vente nationaux.',
    aiExplanation: 'Vos résultats prouvés sur la réduction des coûts sont un atout majeur.',
    potentialScoreGain: 12,
    relativePosition: 8,
    successProbability: 75,
    sector: 'Retail',
    experienceLevel: 'senior',
    location: 'Paris, FR',
    createdAt: '2024-03-22T09:00:00Z'
  },
  ...Array.from({ length: 28 }).map((_, i) => ({
    id: `o${i + 3}`,
    title: i % 2 === 0 ? 'Chef de Projet' : 'Responsable d\'Équipe',
    company: `Entreprise ${i + 3}`,
    matchScore: 60 + Math.random() * 30,
    skillGap: ['Communication'],
    matchedSkills: ['Organisation'],
    requiredSkills: ['Organisation', 'Communication'],
    description: 'Description de l\'opportunité.',
    aiExplanation: "Analyse des preuves en cours...",
    potentialScoreGain: 5 + Math.random() * 20,
    relativePosition: 5 + Math.random() * 20,
    successProbability: 50 + Math.random() * 40,
    sector: i % 4 === 0 ? 'Logistique' : i % 4 === 1 ? 'Santé' : i % 4 === 2 ? 'Énergie' : 'Finance',
    experienceLevel: i % 3 === 0 ? 'junior' : i % 3 === 1 ? 'intermediate' : 'senior',
    location: i % 2 === 0 ? 'Remote' : 'Paris, FR',
    createdAt: new Date(Date.now() - Math.random() * 1000000000).toISOString()
  })) as Opportunity[]
];
